providers = ["python", "node"]  # Python ni birinchi o'ringa qo'yamiz

[phases.setup]
nixPkgs = ["...", "python311"]  # Python 3.11 ni majburiy o'rnatish

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python server.py"